analysis:
  technical_indicators:
    enabled: false
api:
  enabled: false
binance:
  api_key: ''
  api_secret: ''
  base_url: https://api.binance.com
  default_symbols:
  - BTCUSDT
  - ETHUSDT
  - ADAUSDT
  - DOTUSDT
  - LINKUSDT
  - BNBUSDT
  - SOLUSDT
  - MATICUSDT
  max_retries: 3
  requests_per_minute: 1200
  retry_delay: 1.0
  supported_intervals:
  - 1m
  - 5m
  - 15m
  - 30m
  - 1h
  - 4h
  - 1d
  - 1w
  timeout: 30
  weight_per_minute: 6000
cache:
  default_ttl: 3600
  max_size: 1000
  redis:
    db: 0
    host: localhost
    password: null
    port: 6379
    socket_timeout: 5
  ttl_by_type:
    ohlc_data: 1800
    pattern_analysis: 3600
    symbol_info: 86400
    technical_indicators: 900
  type: memory
data:
  bulk_fetch:
    batch_size: 10
    delay_between_requests: 0.5
    max_concurrent_requests: 5
  default_days_back: 30
  default_interval: 1h
  max_days_back: 365
  validation:
    check_duplicates: true
    check_gaps: true
    check_price_anomalies: true
    max_gap_hours: 2
    max_price_change_percent: 50
database:
  cleanup:
    cleanup_interval_hours: 24
    enabled: true
    retention_days: 365
  sqlite:
    check_same_thread: false
    path: data/trading.db
    timeout: 30
  tables:
    ohlc_data:
      indexes:
      - - symbol
        - interval
        - timestamp
      - - timestamp
      name: ohlc_data
    pattern_labels:
      indexes:
      - - symbol
        - interval
        - start_time
      name: pattern_labels
    symbol_metadata:
      indexes:
      - - symbol
      name: symbol_metadata
  type: sqlite
development:
  debug_mode: true
  disable_cache: true
  mock_api: false
  mode: true
labeling:
  enabled: false
logging:
  files:
    api_calls:
      path: logs/api_calls.log
      retention: 7 days
      rotation: 1 day
    errors:
      path: logs/errors.log
      retention: 90 days
      rotation: 1 day
    main:
      compression: gz
      path: logs/trading_app.log
      retention: 30 days
      rotation: 1 day
  format: '{time:YYYY-MM-DD HH:mm:ss} | {level} | {name}:{function}:{line} | {message}'
  level: INFO
  modules:
    binance_client: INFO
    cache: INFO
    data_manager: INFO
    database: INFO
ml:
  enabled: false
monitoring:
  alerts:
    enabled: false
  health_check:
    enabled: true
    interval_minutes: 5
  metrics:
    collection_interval: 60
    enabled: true
